
#include <Arduino.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include "configuration.h"
 
#define OLED_RESET 4
#define LOGO_HEIGHT   32
#define LOGO_WIDTH    61
Adafruit_SSD1306 display(OLED_RESET);

//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char PROGMEM logo80 [] = {
/* 0X00,0X01,0X3D,0X00,0X20,0X00, */
0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X07,0XFF,0XFF,0XFF,0X00,
0X00,0X00,0X01,0X0F,0XFF,0XFF,0XFF,0X00,0X00,0X00,0X03,0X0F,0XFF,0XFF,0XFF,0X00,
0X00,0X00,0X03,0X0F,0XF3,0XFF,0XFF,0X00,0X00,0X00,0X07,0X0F,0XC0,0X70,0X1F,0X00,
0X00,0X00,0X0F,0X0F,0X80,0X71,0X8F,0X00,0X00,0X00,0X1F,0X0F,0X8E,0X31,0X8F,0X00,
0X00,0X00,0X1F,0X0F,0X9F,0X30,0X0F,0X00,0X00,0X00,0X3F,0X0F,0X9F,0X30,0X1F,0X00,
0X00,0X00,0X7F,0X0F,0X9F,0X31,0XFF,0X00,0X00,0X00,0X7F,0X0F,0X8E,0X31,0XFF,0X00,
0X00,0X00,0XFF,0X0F,0XC4,0X71,0XFF,0X00,0X00,0X01,0XFF,0X0F,0XE0,0X71,0XFF,0X00,
0X00,0X03,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,0X00,0X03,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,
0X00,0X07,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,0X00,0X07,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,
0X00,0X0F,0XFF,0X0F,0X80,0X63,0X8F,0X00,0X00,0X1F,0XFF,0X0F,0X8F,0XE1,0X8F,0X00,
0X00,0X3F,0XFF,0X0F,0X9F,0XE1,0X8F,0X00,0X00,0X7F,0XFF,0X0F,0X80,0XE0,0X8F,0X00,
0X00,0X7F,0XFF,0X0F,0X80,0XE4,0X0F,0X00,0X00,0XFF,0XFF,0X0F,0X8F,0XE6,0X0F,0X00,
0X00,0XFF,0XFF,0X0F,0X9F,0XE6,0X0F,0X00,0X01,0XFF,0XFF,0X0F,0X80,0X67,0X0F,0X00,
0X03,0XFF,0XFF,0X0F,0X80,0X67,0X9F,0X00,0X07,0XFF,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,
0X07,0XFF,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,0X0F,0XFF,0XFF,0X0F,0XFF,0XFF,0XFF,0X00,
0X0F,0XFF,0XFE,0X07,0XFF,0XFF,0XFF,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X00,
};

void testdrawbitmap(void) {
  display.clearDisplay();

  display.drawBitmap(
    (display.width()  - LOGO_WIDTH ) / 2,
    (display.height() - LOGO_HEIGHT) / 2,
    logo80, LOGO_WIDTH, LOGO_HEIGHT, 1);
  display.display();
  delay(1000);
  display.clearDisplay();
}

void oledsetup() {
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
  display.display();
  delay(1000);
  display.clearDisplay();
}

 void oledCoursor0(String value0){
    delay(1000);
    display.setTextSize(1);
    display.setTextColor(WHITE);
    display.setCursor(0,0);
    display.println(value0);
    display.display();
    display.clearDisplay();
 }

void oledCoursor10(String value0){
    delay(1000);
    display.setTextSize(1);
    display.setTextColor(WHITE);
    display.setCursor(0,10);
    display.println(value0);
    display.display();
    display.clearDisplay();
 }

  void oledloop() {
  delay(500);
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.setCursor(0,0);
  display.println("Bootsdaten Sensor");
  display.setCursor(0,10);
  display.println(sI2C_Status);
  display.setCursor(0,20);
  display.print("Tiefgang: ");
  display.println(fAbsTief);
  display.display();
  display.clearDisplay();
}